"""fix nullable fields

Revision ID: 03ba09f392f1
Revises: c01e0502f7c8
Create Date: 2025-10-06 22:42:00.673856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ba09f392f1'
down_revision: Union[str, None] = 'c01e0502f7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'message_user',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'message_user',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
